/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#d3e4fe",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#38485d",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#00164e",
        "background": "#f7f9fb",
        "tertiary-container": "#6e2c00",
        "on-surface-variant": "#444651",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c5c5d3",
        "surface": "#f7f9fb",
        "primary-fixed": "#dce1ff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#505f76",
        "on-primary-fixed-variant": "#264191",
        "surface-dim": "#d8dadc",
        "secondary-container": "#d0e1fb",
        "on-primary-container": "#90a8ff",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed-dim": "#ffb691",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#341100",
        "on-secondary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "inverse-primary": "#b6c4ff",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#f39461",
        "primary-fixed-dim": "#b6c4ff",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#54647a",
        "surface-tint": "#4059aa",
        "tertiary": "#4b1c00",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary-fixed-variant": "#773205",
        "outline": "#757682",
        "on-surface": "#191c1e",
        "primary": "#00236f",
        "primary-container": "#1e3a8a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sidebar-width": "280px",
        "md": "1.5rem",
        "gutter": "24px",
        "lg": "2rem",
        "xl": "3rem",
        "sm": "1rem",
        "base": "4px",
        "max-content-width": "1440px",
        "xs": "0.5rem"
      },
      "fontFamily": {
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "500"}],
        "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-bold": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};
